export default {
  USER_STATUS: {
    ACTIVE: "ACTIVE",
    DROPPED_OFF: "DROPPED_OFF",
    DUE_PLAN_PURCHASE: "DUE_PLAN_PURCHASE",
    EXPIRED: "EXPIRED",
    USER_CONFIRM_VMN: "USER_CONFIRM_VMN",
    FREE_TRIAL: "FREE_TRIAL",
    TERMINATED: "TERMINATED",
    DELETED: "DELETED",
    LIVE: "LIVE",
    SUSPENDED: "SUSPENDED",
  },
};
