version: 0.0
os: linux
files:
  - source: /
    destination: /home/captain/deployments/sample-micro-service

hooks:
  # ApplicationStop:
  #   - location: shells/stop_server.sh
  #     timeout: 300
  AfterInstall:
    - location: shells/install_dependencies.sh
      timeout: 300
  ApplicationStart:
    - location: shells/start_server.sh
      timeout: 300
  ValidateService:
    - location: shells/validate_service.sh
      timeout: 60
