# https://support.atlassian.com/bitbucket-cloud/docs/use-docker-images-as-build-environments/
# image: atlassian/default-image:2
image: node:16.13.2

pipelines:
  branches:
    dev:
      - step:
          caches:
            - node
          name: Install & Eslint
          script:
            - echo $DEPLOYMENT_GROUP
            - npm install
            - npm run lint
      - step:
          name: Deploy to Dev
          deployment: Dev
          script:
            - apt-get update -y
            - apt-get install -y zip
            - zip -r app.zip .
            - echo $DEPLOYMENT_GROUP
            - echo $APPLICATION_NAME
            - pipe: atlassian/aws-code-deploy:1.1.0
              variables:
                AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
                AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
                AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
                APPLICATION_NAME: $APPLICATION_NAME
                S3_BUCKET: $S3_BUCKET
                COMMAND: "upload"
                ZIP_FILE: "app.zip"
                VERSION_LABEL: $S3_VERSION_LABEL
            - pipe: atlassian/aws-code-deploy:1.1.0
              variables:
                AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
                AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
                AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
                APPLICATION_NAME: $APPLICATION_NAME
                DEPLOYMENT_GROUP: $DEPLOYMENT_GROUP
                S3_BUCKET: $S3_BUCKET
                COMMAND: "deploy"
                WAIT: "true"
                VERSION_LABEL: $S3_VERSION_LABEL
                IGNORE_APPLICATION_STOP_FAILURES: "true"
                FILE_EXISTS_BEHAVIOR: "OVERWRITE"
    master:
      - step:
          caches:
            - node
          name: Install & Eslint
          script:
            - echo $DEPLOYMENT_GROUP
            - npm install
            - npm run lint
      - step:
          name: Deploy to Production
          deployment: Production
          trigger: manual
          script:
            - apt-get update -y
            - apt-get install -y zip
            - zip -r app.zip .
            - echo $DEPLOYMENT_GROUP
            - echo $APPLICATION_NAME
            - pipe: atlassian/aws-code-deploy:1.1.0
              variables:
                AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
                AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
                AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
                APPLICATION_NAME: $APPLICATION_NAME
                S3_BUCKET: $S3_BUCKET
                COMMAND: "upload"
                ZIP_FILE: "app.zip"
                VERSION_LABEL: $S3_VERSION_LABEL
            - pipe: atlassian/aws-code-deploy:1.1.0
              variables:
                AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
                AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
                AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
                APPLICATION_NAME: $APPLICATION_NAME
                DEPLOYMENT_GROUP: $DEPLOYMENT_GROUP
                S3_BUCKET: $S3_BUCKET
                COMMAND: "deploy"
                WAIT: "true"
                VERSION_LABEL: $S3_VERSION_LABEL
                IGNORE_APPLICATION_STOP_FAILURES: "true"
                FILE_EXISTS_BEHAVIOR: "OVERWRITE"
