#!/bin/sh
. "$(dirname "$0")/_/husky.sh"
# diff filter d exlucdes deleted files. https://git-scm.com/docs/git-diff#Documentation/git-diff.txt---diff-filterACDMRTUXB82308203
for file in $(git diff --diff-filter=d --cached --name-only | grep -E '\.(js)$')
do
  # fix possible issues
  node_modules/.bin/eslint "$file" --fix
  # Add files to staging
  git add $file
  # run eslint only on staged changes, not any un-staged changes
  git show ":$file" | node_modules/.bin/eslint --stdin --stdin-filename "$file" --cache --cache-strategy content
  if [ $? -ne 0 ]; then
    echo "ESLint failed: '$file'"
    exit 1 # exit with failure status
  fi
done

